1_basic_scala.ipynb
=> Fix broken json in basic scala

images/shifter4.svg
=> Fix diagram for shift register to not add delay to input.

README.md
Update windows install section based on user feedback.
=> Update windows installation instructions in README

2.4_sequential_logic.ipynb
@sehuang noted in #36 that step() was called after expect(), which doesn't make much sense.
=> Fix parameterized shift register test and solution.

README.md, binder/apt.txt, binder/postBuild, environment.yml
- Adds binder/* to enable binder to create a docker image of chisel-bootcamp with the almond scala jupyter kernel
- Adds a binder badge to the README.md
=> Enable Binder to work

3.4_functional_programming.ipynb
=> Make neuron thresholds consistent.

Install.md, README.md
Update instructions to use 2.12.
Also, split installations out of main README into its own file.
=> 2.12 instructions

source/load-ivy.sc
This is the magic incantation. I figured it out once, forgot it, and then figured it out a second time.
Closes #45.
=> Add -Xsource:2.11 to ammonite

1_intro_to_scala.ipynb
=> Fix usage of util.Random.

Install.md, source/load-ivy.sc
=> Add some starter code and instructions for using a proxy.

2.1_first_module.ipynb
Tone down from "crazy Scala" to be lass scary
=> Tone down from crazy Scala to sound less scary

2.2_comb_logic.ipynb, 3.2_interlude.ipynb
=> Fix old website links

OneDayAgenda.md
This adds a suggested simple schedule for getting 
through these materials in a one day session.
=> Add a one day agenda

0_demo.ipynb, README.md, source/load-ivy.sc
This PR creates a 0th bootcamp module that demonstrates the power of Chisel and FIRRTL. Included is infrastructure integrating the [firrtl-diagrammer](https://github.com/freechipsproject/diagrammer).
TODO:
Work Future PRs:
- Add FIRRTL section demonstrating transformations
=> Add Demo Notebook [Do not merge yet]

3.3_higher-order_functions.ipynb
These are some personal fixes during my going through the Chisel Bootcamp. :smile:
=> 3.3_higher-order_functions.ipynb: small fixes

binder/postBuild
This seemed to fix it in local linux  box
Hopefully this fixes Issue #100
=> There is a problem with coursier cli installation.

OneDayAgenda.md
Hope this kicks off new Binder
=> Remove Apex

source/load-ivy.sc
It turns out that both authors independently came up with the same fix, so creating one commit to merge both PRs.
=> Merge #95 and #92

binder/postBuild
Worth a try? The setup works fine for me locally.
=> Attempted binder fix

Install.md
- Coursier has changed its interface
- Use OpenJDK to avoid Oracle paywall
- Misc tweaks
=> Update Windows instructions for September 2020

3.4_functional_programming.ipynb, 4.4_firrtl_add_ops_per_module.ipynb, runtest.py, source/load-ivy.sc
Fix changes to running diagrammer due to diagrammer changes
Required [diagammer pr#67](https://github.com/freechipsproject/diagrammer/pull/67) to be backported first
=> Fixes for diagrammer pr 67

2.3_control_flow.ipynb
=> Initialize default nextState

3.3_higher-order_functions.ipynb
few things I noticed while working through chapter 3.3
=> fixing some minor typos in chapter '3.3 higher order functions'

3.6_types.ipynb
few things I noticed during chapter 3.6 aside from #159 and #133
=> chapter 3.6: minor fixes for typos and excercises
